{% set name = "model_catalogs" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/model_catalogs-{{ version }}.tar.gz
  sha256: ef84364e11967ed81773f8b6dd6b66f0f579310db8d2373682a15665c11839a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - intake-xarray
    - netcdf4
    - dask-core
    - cf_xarray
    - datetimerange
    - mc-goods
    - numpy
    - siphon
    - pandas
    - intake
    - appdirs
    - requests
    - xarray
    - pip

test:
  imports:
    - model_catalogs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NOAA-ORR-ERD/model_catalogs
  summary: Catalogs for known models
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
    - ChrisBarker-NOAA
